fix(proxy, generator) fix internal call bug
OpenClassrooms/ServiceProxy pull request #6
Opened 2020-04-16 08:20 UTC by sidux

# Summary :
In this PR with the [PR](https://github.com/OpenClassrooms/ServiceProxyBundle/pull/6) the two issues detailed bellow :

##Internal methods calls ignore decoration (cache in our case) :
If we take a method `foo` which calls a method `bar` that have a cache annotation, the cache will be ignored.
The proxy generated will replace all methods in the class even the ones without annotations with a call to the child (real subject) class.
So `foo` of the child class will call also `bar` of that same class and thus the proxy (parent) will be ignored.
### solution:
Overriding only the annotated methods will resolve all cases where other methods call it, since the proxy inherits from the subject class
the context will stay on the proxy and thus calling the correct method.
This solution has some limitations though, the private properties states will be lost. The workaround found is to copy the state of the subject class to
the proxy and accessing private properties using the `Closure::call` php method.
*Calling the `$factoryDefinition->setMethodCalls($definition->getMethodCalls());` in ServiceProxyBundle Compiler Pass is essential to keep to sync the state of the source class and the proxy when decorating.*

##Using the ServiceProxyBundle with UseCaseBundle ignores proxies:
This issue is self-explanatory.
### solution
The solution is to make the ServiceProxyBundle compiler pass before the UseCaseBundle one, and keep the annotation and there imports
in the generated proxy.
This solution and specially keeping the use statements causes an issue with the default proxy generation strategy in the DEV environment, because it uses the `eval` which
doesn't support php autoload and thus can't resolve imports. the workaround was creating a new generation strategy that generates the proxy in a tmp folder
and requiring it just after and overriding it on each container compilation, we still have some limitations mainly a possible performance drop in the
container compilation in DEV environment.
*Calling the `$factoryDefinition->setTags($definition->getTags());` in ServiceProxyBundle Compiler Pass is essential to keep tags of the source service which makes the UseCaseBundle Compiler take into account proxies.*

2020-09-01 09:07 UTC, yassavic requested changes

2020-09-01 09:07 UTC, yassavic commented on tests/ServiceProxyCacheTest.php
> +    public function WithInternalCall_ReturnData()
should be camelCased

2020-09-01 09:07 UTC, yassavic commented on tests/ServiceProxyBuilderTest.php
>      public function WithCacheAnnotationWithoutCacheProvider_ThrowException()
should be camelCased

2021-04-16 17:08 UTC, sidux commented
This lib needs full rework with proper proxy generation strategy. cf [smart reference](https://github.com/Ocramius/ProxyManager/blob/2.12.x/examples/smart-reference.php)

2021-04-16 17:08 UTC, closed without merging